name: "yolo26_preprocess"
backend: "python"
max_batch_size: 1

input [
  {
    name: "input_images"
    data_type: TYPE_UINT8
    dims: [3, 1080, 1920]
  }
]

output [
  {
    name: "preprocessed_image"
    data_type: TYPE_FP32
    dims: [3, 640, 640]
  }
]

instance_group [
  {
    kind: KIND_CPU
    count: 1
  }
]
