name: "rfdetr_preprocess"
backend: "python"
max_batch_size: 8

# Input H,W must match streammux dims (currently 720x1280 in config.yaml).
# Change here if you change streammux dims.
input [
  {
    name: "input_images"
    data_type: TYPE_UINT8
    dims: [3, 720, 1280]
  }
]

output [
  {
    name: "preprocessed_image"
    data_type: TYPE_FP32
    dims: [3, 704, 704]
  }
]

instance_group [
  {
    kind: KIND_GPU
    count: 1
    gpus: [0]
  }
]

parameters: [
  { key: "FORCE_CPU_ONLY_INPUT_TENSORS"  value: { string_value: "no" } },
  { key: "FORCE_CPU_ONLY_OUTPUT_TENSORS" value: { string_value: "no" } }
]
