name: "yolo26x_ensemble"
platform: "ensemble"
max_batch_size: 8

input [
  {
    name: "input_images"
    data_type: TYPE_UINT8
    dims: [3, 1080, 1920]
  }
]

output [
  {
    name: "ensemble_labels"
    data_type: TYPE_INT64
    dims: [300]
  },
  {
    name: "ensemble_scores"
    data_type: TYPE_FP32
    dims: [300]
  },
  {
    name: "ensemble_boxes"
    data_type: TYPE_FP32
    dims: [300, 4]
  }
]

ensemble_scheduling {
  step [
    {
      model_name: "yolo26_preprocess"
      model_version: 1
      input_map {
        key: "input_images"
        value: "input_images"
      }
      output_map {
        key: "preprocessed_image"
        value: "preprocessed_image"
      }
    },
    {
      model_name: "yolo26x"
      model_version: 1
      input_map {
        key: "images"
        value: "preprocessed_image"
      }
      output_map {
        key: "output0"
        value: "raw_output"
      }
    },
    {
      model_name: "yolo26_postprocess"
      model_version: 1
      input_map {
        key: "raw_output"
        value: "raw_output"
      }
      output_map {
        key: "output_labels"
        value: "ensemble_labels"
      }
      output_map {
        key: "output_scores"
        value: "ensemble_scores"
      }
      output_map {
        key: "output_boxes"
        value: "ensemble_boxes"
      }
    }
  ]
}
